databases:
  - name: score-students-db
    plan: free
    databaseName: score_students_db_ovfz
    user: score_students_db_ovfz_user

services:
  - type: web
    plan: free
    name: random_forest_simulator
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn random_forest_simulator.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: score_students_db_ovfz
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 10
      - key: DEBUG
        value: 'False'
      - key: MODE
        value: 'development'